version: '3.8'
services:
  authpostgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: strongPassword
      POSTGRES_USER: admin_user
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    networks:
      - my-network

  myapp:
    build: .
    depends_on:
      - authpostgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authpostgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: strongPassword
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
